language: cpp
compiler:
  - clang
notifications:
  email: 
      - code@donner.at
before_install:
  - sudo add-apt-repository ppa:staticfloat/julia-deps -y
  - sudo add-apt-repository ppa:staticfloat/juliareleases -y
  - sudo apt-get update -qq -y
  - sudo apt-get install libpcre3-dev julia -y
script:
  - julia -e 'Pkg.init(); Pkg.add("FactCheck")'
  - julia -e 'Pkg.clone("https://github.com/rened/QuickShiftClustering.jl.git")'
  - julia -e 'Pkg.resolve(); Pkg.checkout("ProgressMeter")'
  - julia ~/.julia/v0.3/QuickShiftClustering/test/runtests.jl
